In [2]:
#数据清洗和准备

In [3]:
#7.1处理缺失数据

In [6]:
import numpy as np
import pandas as pd
string_data=pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [7]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [14]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [11]:
string_data.isnull

<bound method Series.isnull of 0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object>

In [15]:
string_data[0]=None

In [16]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [19]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [23]:
for i in string_data.index:
    if string_data[i]==None:
        string_data[i]=1
string_data

0            1
1    artichoke
2          NaN
3      avocado
dtype: object

In [24]:
#滤除缺失字段

In [25]:
from numpy import nan as NA
data=pd.Series([1,NA,3.5,NA,7])

In [26]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [27]:
data.dropna() ##返回一个过滤NAN值的对象，不改变原来数组

0    1.0
2    3.5
4    7.0
dtype: float64

In [28]:
#=======等价于=========>

In [29]:
data[data.notnull()] #每一行被每一个函数单独处理

0    1.0
2    3.5
4    7.0
dtype: float64

In [30]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [31]:
data=pd.DataFrame([[1.,6.5,3.],[1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])

In [40]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [44]:
data[0]

0    1.0
1    1.0
2    NaN
3    NaN
Name: 0, dtype: float64

In [36]:
cleaned=data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [37]:
data.dropna(how='all') #删除全部为null的行

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [38]:
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [39]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [48]:
s1=np.array([1,2,3,4])
s1


array([1, 2, 3, 4])

In [46]:
s2=pd.Series(np.array([1,2,3,4]))
s2

0    1
1    2
2    3
3    4
dtype: int32

In [49]:
df=pd.DataFrame(np.random.randn(7,3))

In [50]:
df.iloc[:4,1]=NA  #[]里面为（行，列），:4 ==》 0,1,2,3
df.iloc[:2,2]=NA
df

0         1         2
0  0.609655       NaN       NaN
1  0.375896       NaN       NaN
2 -0.538401       NaN  0.844934
3 -0.270612       NaN -1.143042
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [51]:
a=np.random.randn(7,3)
a

array([[-1.07210066, -1.21419925, -0.6745719 ],
       [ 0.35335943, -2.83448947, -0.06205978],
       [-0.56990929,  0.2211158 , -0.1487217 ],
       [ 1.23760385,  1.01134944,  1.30655826],
       [-0.38652039,  0.37927109, -0.53415385],
       [-0.55263024,  0.60508635,  0.68056421],
       [-1.30859962,  1.75891173,  0.42412811]])

In [52]:
b=np.random.randn(3)

In [53]:
b

array([-0.2266431 ,  0.22532079,  0.24641435])

In [55]:
df.dropna()

0         1         2
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [58]:
df.dropna(thresh=2)

0         1         2
2 -0.538401       NaN  0.844934
3 -0.270612       NaN -1.143042
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [65]:
df.dropna(thresh=3)

0         1         2
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [66]:
# fill the nan

In [67]:
df.fillna(0)

0         1         2
0  0.609655  0.000000  0.000000
1  0.375896  0.000000  0.000000
2 -0.538401  0.000000  0.844934
3 -0.270612  0.000000 -1.143042
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [68]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.609655  0.500000  0.000000
1  0.375896  0.500000  0.000000
2 -0.538401  0.500000  0.844934
3 -0.270612  0.500000 -1.143042
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [70]:
_ = df.fillna(0,inplace=True) #really fillnan

In [73]:
df

0         1         2
0  0.609655  0.000000  0.000000
1  0.375896  0.000000  0.000000
2 -0.538401  0.000000  0.844934
3 -0.270612  0.000000 -1.143042
4  1.494656  0.853670 -1.225766
5  0.205779 -0.269723  0.173132
6 -0.242430 -0.021205 -1.073195

In [74]:
df=pd.DataFrame(np.random.randn(6,3))

In [75]:
df.iloc[2:,1]=NA

In [76]:
df.iloc[4:,2]=NA

In [77]:
df

0         1         2
0  1.168658 -0.260098  0.913877
1 -1.571803  0.516543  1.704443
2  0.351405       NaN  2.368914
3 -0.040284       NaN  1.582334
4 -1.482931       NaN       NaN
5  0.166731       NaN       NaN

In [83]:
df.fillna(method='ffill')  #ffill为固定参数，瞎写会报错啊

0         1         2
0  1.168658 -0.260098  0.913877
1 -1.571803  0.516543  1.704443
2  0.351405  0.516543  2.368914
3 -0.040284  0.516543  1.582334
4 -1.482931  0.516543  1.582334
5  0.166731  0.516543  1.582334

In [81]:
df

0         1         2
0  1.168658 -0.260098  0.913877
1 -1.571803  0.516543  1.704443
2  0.351405       NaN  2.368914
3 -0.040284       NaN  1.582334
4 -1.482931       NaN       NaN
5  0.166731       NaN       NaN

In [85]:
df.fillna(method='ffill',limit=2)

0         1         2
0  1.168658 -0.260098  0.913877
1 -1.571803  0.516543  1.704443
2  0.351405  0.516543  2.368914
3 -0.040284  0.516543  1.582334
4 -1.482931       NaN  1.582334
5  0.166731       NaN  1.582334

In [86]:
data=pd.Series([1.,NA,3.5,NA,7])

In [87]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [88]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [89]:
#数据的转换

In [97]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})

In [98]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [99]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [101]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [102]:
data['v1']= range(7)

In [103]:
data.drop_duplicates(['k1']) #duplicated 和 drop_duplicates 默认保留的是第一个出现的值组合。传入
#keep='last'则保留最后一个：

k1  k2  v1
0  one   1   0
1  two   1   1

In [104]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [105]:
#  trunsformat

In [108]:
data=pd.DataFrame({'food': ['bacon', 'pulled pork','bacon','Pastrami', 'corned beef','Bacon','pastrami', 'honey ham', 'novalox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5,6]})

In [109]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8      novalox     6.0

In [110]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [111]:
lowercasted=data['food'].str.lower()

In [112]:
lowercasted

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8        novalox
Name: food, dtype: object

In [120]:
data['animal']=lowercasted.map(meat_to_animal)

In [121]:
data

food  ounces animal
0        bacon     4.0    pig
1  pulled pork     3.0    pig
2        bacon    12.0    pig
3     Pastrami     6.0    cow
4  corned beef     7.5    cow
5        Bacon     8.0    pig
6     pastrami     3.0    cow
7    honey ham     5.0    pig
8      novalox     6.0    NaN

In [122]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

KeyError: 'novalox'

In [123]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [124]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [125]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [126]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [127]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [128]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [129]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])

In [130]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [131]:
transform = lambda x: x[:4].upper()

In [132]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [133]:
data.index=data.index.map(transform)

In [134]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [135]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [136]:
data.rename(index={'OHIO': 'INDIANA'},columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [137]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [138]:
#离散化

In [139]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [140]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [141]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [142]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [143]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [145]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged','Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [146]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.28, 0.5], (0.71, 0.92], (0.07, 0.28], (0.28, 0.5], (0.71, 0.92], ..., (0.07, 0.28], (0.5, 0.71], (0.71, 0.92], (0.07, 0.28], (0.07, 0.28]]
Length: 20
Categories (4, interval[float64]): [(0.07, 0.28] < (0.28, 0.5] < (0.5, 0.71] < (0.71, 0.92]]

In [148]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4) 
cats

[(-2.967, -0.711], (0.683, 3.347], (-0.0172, 0.683], (-0.0172, 0.683], (0.683, 3.347], ..., (-2.967, -0.711], (-2.967, -0.711], (-0.0172, 0.683], (0.683, 3.347], (0.683, 3.347]]
Length: 1000
Categories (4, interval[float64]): [(-2.967, -0.711] < (-0.711, -0.0172] < (-0.0172, 0.683] < (0.683, 3.347]]

In [149]:
pd.value_counts(cats)


(0.683, 3.347]       250
(-0.0172, 0.683]     250
(-0.711, -0.0172]    250
(-2.967, -0.711]     250
dtype: int64

In [150]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.208, -0.0172], (-0.0172, 1.364], (-0.0172, 1.364], (-0.0172, 1.364], (-0.0172, 1.364], ..., (-1.208, -0.0172], (-2.967, -1.208], (-0.0172, 1.364], (1.364, 3.347], (-0.0172, 1.364]]
Length: 1000
Categories (4, interval[float64]): [(-2.967, -1.208] < (-1.208, -0.0172] < (-0.0172, 1.364] < (1.364, 3.347]]

In [151]:
#过滤盒检测异常值


In [152]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.022190     0.018694    -0.044036    -0.000178
std       1.004117     0.998434     1.045390     1.009665
min      -2.985470    -2.957584    -3.138471    -3.231471
25%      -0.611226    -0.672199    -0.723705    -0.676014
50%       0.019992     0.068435    -0.066832    -0.004580
75%       0.694677     0.675181     0.655540     0.680315
max       3.170196     3.110674     3.360081     3.268660

In [153]:
col = data[2]
col[np.abs(col) > 3]

341    3.360081
541    3.357117
711    3.250911
802   -3.138471
Name: 2, dtype: float64

In [154]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
207  3.170196  0.112847  0.258245 -0.296262
341 -0.967774  0.332513  3.360081  0.279917
363  3.073946 -0.768052  0.615230  1.024167
510 -0.153217 -0.014061  0.066273  3.019970
541  0.400145  1.077987  3.357117  0.542354
575  0.318227 -0.096184  0.522149  3.118763
596  1.262871  1.519599  1.173170 -3.231471
664  3.095531  1.303759 -0.420711 -1.258255
711  0.662942  0.866022  3.250911  0.044650
776 -0.215510  1.895369 -1.716679  3.223197
802  1.523373  0.047899 -3.138471 -0.217277
921  0.042647 -2.345683 -0.556714  3.081361
923  1.875440  0.218334 -1.684835  3.268660
948 -1.343949  3.110674 -0.779647  0.805470

In [156]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021851     0.018583    -0.044865    -0.000659
std       1.003086     0.998097     1.042008     1.006757
min      -2.985470    -2.957584    -3.000000    -3.000000
25%      -0.611226    -0.672199    -0.723705    -0.676014
50%       0.019992     0.068435    -0.066832    -0.004580
75%       0.694677     0.675181     0.655540     0.680315
max       3.000000     3.000000     3.000000     3.000000

In [157]:
data.describe

<bound method NDFrame.describe of             0         1         2         3
0   -0.936469 -1.058551  0.094454 -0.165119
1    0.626475  1.046821 -1.242660  1.106775
2   -0.549212 -1.466029 -0.814011  0.239649
3   -0.205470  0.747532  1.133107 -1.546677
4   -0.239138  1.035284  1.196408 -2.533162
5    0.510681 -1.042951 -0.708364  1.014865
6    1.158752  0.460997  1.220377  0.291359
7    1.405911  0.551745 -0.253570 -0.281964
8    1.151655  0.339897  0.289333 -0.870855
9   -0.490656 -0.526625  2.126746  1.237111
10  -0.483032  0.156387 -1.212958  0.661690
11  -1.383344  0.810491 -0.098990  0.014958
12   1.841782  0.692428 -0.881681 -0.427215
13   0.901382 -2.576595 -0.966464 -0.460952
14   0.762856  0.844751 -0.496354  0.012246
15   0.122942  1.543453 -2.369951 -0.742977
16   0.228837 -0.689964 -0.153291 -0.358108
17  -1.037023 -1.039807  0.891393 -0.433465
18  -0.340124  0.567116  0.735265  0.502434
19   0.797256 -2.032142  0.629485 -0.070175
20  -1.515228 -0.051400  0.545963 -1.60355

In [158]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1  1.0  1.0 -1.0  1.0
2 -1.0 -1.0 -1.0  1.0
3 -1.0  1.0  1.0 -1.0
4 -1.0  1.0  1.0 -1.0

In [159]:
#排列和随机采样

In [160]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([4, 3, 1, 2, 0])

In [161]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [162]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [163]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15

In [164]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

3    6
0    5
4    4
3    6
3    6
0    5
2   -1
4    4
3    6
0    5
dtype: int64

In [165]:
#计算指标和哑变量

In [167]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [168]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [12]:
import pandas as pd
import numpy as np
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('C:/Users/Mr.Song/bigdaata/movies.dat',sep='::', header=None, names=mnames)

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: read_table is deprecated, use read_csv instead.
  after removing the cwd from sys.path.
D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


In [5]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [7]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [13]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [14]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [15]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [16]:
for i, gen in enumerate(movies.genres):
     indices = dummies.columns.get_indexer(gen.split('|'))
     dummies.iloc[i, indices] = 1

In [17]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [18]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [19]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [20]:
#字符串操作

In [24]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [25]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [26]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [27]:
'::'.join(pieces)

'a::b::guido'

In [28]:
'guido' in val

True

In [29]:
val.index(',')

1

In [30]:
val.find(":")

-1

In [32]:
val.index(":")

ValueError: substring not found

In [33]:
val.count(",")

2

In [34]:
val.replace(",","::")

'a::b:: guido'

In [35]:
val.replace(",","")

'ab guido'

In [36]:
#zhengce

In [37]:
import re

In [38]:
text = "foo bar\t baz \tqux"

In [39]:
re.split("\s+",text)

['foo', 'bar', 'baz', 'qux']

In [40]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [41]:
regex.findall(text)

[' ', '\t ', ' \t']

In [42]:
regex.findall(text)

[' ', '\t ', ' \t']

In [43]:
 m = regex.search(text)

In [44]:
m

<re.Match object; span=(3, 4), match=' '>

In [45]:
text[m.start():m.end()]

' '

In [46]:
print(regex.match(text))

None


In [47]:
print(regex.sub('REDACTED', text))

fooREDACTEDbarREDACTEDbazREDACTEDqux


In [49]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [54]:
regex = re.compile(pattern, flags=re.IGNORECASE)
regex 

re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})',
re.IGNORECASE|re.UNICODE)

In [51]:
m = regex.match('wesm@bright.net')

In [52]:
m.groups()

('wesm', 'bright', 'net')

In [53]:
regex.findall(text)

[]

In [56]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text))

foo bar	 baz 	qux


In [ ]:
# shilaingahu

In [60]:
data = {'Dave': 'dave@google.com', 'Steve':'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [61]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [63]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [64]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [65]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [67]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [68]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [69]:
 matches = data.str.match(pattern, flags=re.IGNORECASE)

In [70]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [71]:
#8 数据的整合：聚合，合并和重塑

In [72]:
data = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c',
'd', 'd'], [1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [73]:
data

a  1    1.007189
   2   -1.296221
   3    0.274992
b  1    0.228913
   3    1.352917
c  1    0.886429
   2   -2.001637
d  2   -0.371843
   3    1.669025
dtype: float64

In [74]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [75]:
data['b']


1    0.228913
3    1.352917
dtype: float64

In [76]:
data['b':'c']

b  1    0.228913
   3    1.352917
c  1    0.886429
   2   -2.001637
dtype: float64

In [77]:
data.loc[['b', 'd']]

b  1    0.228913
   3    1.352917
d  2   -0.371843
   3    1.669025
dtype: float64

In [78]:
 data.loc[:, 2]

a   -1.296221
c   -2.001637
d   -0.371843
dtype: float64

In [79]:
data.unstack()

1         2         3
a  1.007189 -1.296221  0.274992
b  0.228913       NaN  1.352917
c  0.886429 -2.001637       NaN
d       NaN -0.371843  1.669025

In [80]:
data.unstack().stack()

a  1    1.007189
   2   -1.296221
   3    0.274992
b  1    0.228913
   3    1.352917
c  1    0.886429
   2   -2.001637
d  2   -0.371843
   3    1.669025
dtype: float64

In [81]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), index=[['a', 'a', 'b', 'b'], [1, 2, 1,
2]], columns=[['Ohio', 'Ohio', 'Colorado'], ['Green', 'Red', 'Green']])

In [82]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [83]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [84]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [85]:
#重排和分级排序

In [86]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [87]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [88]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [89]:
#根据级别汇总统计

In [90]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [91]:
frame.sum(level='color', axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [92]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1), 'c': ['one', 'one', 'one', 'two',
'two', 'two', 'two'], 'd': [0, 1, 2, 0, 1, 2, 3]})

In [93]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [94]:
frame2 = frame.set_index(['c', 'd'])

In [95]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [96]:
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [97]:
 frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [98]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a','b'], 'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})

In [99]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [100]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [101]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [102]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [103]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a',
'b'], 'data1': range(7)})

In [104]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [105]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})

In [106]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [107]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [108]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [109]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],'data2': range(5)})

In [110]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [111]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [112]:
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [113]:
pd.merge(df1, df2, how='inner')

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [119]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'], 'key2': ['one', 'two', 'one'], 'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'], 'key2': ['one', 'one', 'one', 'two'],'rval': [4, 5, 6, 7]})

In [120]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [121]:
 pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [122]:
pd.merge(left, right, on='key1', suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [123]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a','b'])

In [124]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [125]:
right1

group_val
a        3.5
b        7.0

In [126]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [127]:
 pd.merge(left1, right1, left_on='key', right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [129]:
 arr = np.arange(12).reshape((3, 4))

In [130]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [136]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [135]:
pd.concat([s1, s2, s3], axis=1)

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [137]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [138]:
pd.concat([s1, s4], axis=1)

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [139]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [140]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [142]:
result = pd.concat([s1, s1, s3], keys=['one','two','three'])

In [143]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [144]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [145]:
pd.concat([s1, s2, s3], axis=1, keys=['one','two', 'three'])

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [150]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a','b', 'c'], columns=['one', 'two'])

In [151]:
 df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2),
index=['a', 'c'], columns=['three', 'four'])

In [153]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [149]:
df2

three  four
a      5     6
c      7     8

In [154]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [155]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [156]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'], names=['upper', 'lower'])

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [157]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a','b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b','d', 'a'])

In [158]:
df1

a         b         c         d
0 -0.438570 -0.539741  0.476985  3.248944
1 -1.021228 -0.577087  0.124121  0.302614
2  0.523772  0.000940  1.343810 -0.713544

In [159]:
df2

b         d         a
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934

In [160]:
pd.concat([df1, df2], ignore_index=True)

D:\devs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0 -0.438570 -0.539741  0.476985  3.248944
1 -1.021228 -0.577087  0.124121  0.302614
2  0.523772  0.000940  1.343810 -0.713544
3 -1.860761 -0.831154       NaN -2.370232
4 -1.265934 -0.860757       NaN  0.560145

In [161]:
 a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],index=['f', 'e', 'd', 'c', 'b', 'a'])

In [162]:
b = pd.Series(np.arange(len(a), dtype=np.float64), index=['f', 'e', 'd', 'c', 'b', 'a'])

In [163]:
b[-1] = np.nan
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [164]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [165]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [166]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [167]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],'b': [np.nan, 2., np.nan, 6.],'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],'b': [np.nan, 3., 4., 6., 8.]})

In [168]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [169]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [170]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [171]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)), index=pd.Index(['Ohio','Colorado'],ame='state'), columns=pd.Index(['one', 'two','three'],name='number'))

In [172]:
data

number    one  two  three
Ohio        0    1      2
Colorado    3    4      5

In [173]:
result = data.stack()

In [174]:
result

          number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [175]:
 result.unstack()

number    one  two  three
Ohio        0    1      2
Colorado    3    4      5

In [176]:
result.unstack(0)

Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [178]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])

In [179]:
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])

In [180]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [181]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [183]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [184]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [185]:
df = pd.DataFrame({'left': result, 'right': result + 5}, columns=pd.Index(['left', 'right'],name='side'))

In [186]:
df

side             left  right
         number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [189]:
# kuangeshi xuanjuanwei changgeshi

In [190]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],'A': [1, 2, 3],'B': [4, 5, 6], 'C': [7, 8, 9]})
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [191]:
melted = pd.melt(df, ['key'])
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [192]:
reshaped = melted.pivot('key', 'variable', 'value')
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [193]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [194]:
pd.melt(df, id_vars=['key'], value_vars=['A', 'B'])

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [195]:
pd.melt(df, value_vars=['A', 'B', 'C'])

variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [196]:
 pd.melt(df, value_vars=['key', 'A', 'B'])

variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6