In [63]:
import pandas as pd #pandas 有个主要的数据结构 Series 和 DataFrame
import numpy as np
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj[0]

4

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2["a"]

-5

In [14]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [19]:
np.exp(obj2)

NameError: name 'np' is not defined

In [20]:
'b' in obj2

True

In [21]:
'e' in obj2

False

In [23]:
sdata = {'0hio':3500,'Texas':7100,'Oregon':1600,'Utah':500}
obj3 = pd.Series(sdata)
obj3

0hio      3500
Texas     7100
Oregon    1600
Utah       500
dtype: int64

In [26]:
states = ['Oregon','Texas','ccc','Utah']
obj4 = pd.Series(sdata,index = states)
obj4

Oregon    1600.0
Texas     7100.0
ccc          NaN
Utah       500.0
dtype: float64

In [27]:
pd.isnull(obj4)

Oregon    False
Texas     False
ccc        True
Utah      False
dtype: bool

In [28]:
pd.notnull(obj4)

Oregon     True
Texas      True
ccc       False
Utah       True
dtype: bool

In [29]:
obj4.isnull()

Oregon    False
Texas     False
ccc        True
Utah      False
dtype: bool

In [30]:
obj3 + obj4

0hio          NaN
Oregon     3200.0
Texas     14200.0
Utah       1000.0
ccc           NaN
dtype: float64

In [31]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
Oregon    1600.0
Texas     7100.0
ccc          NaN
Utah       500.0
Name: population, dtype: float64

In [32]:
obj4

state
Oregon    1600.0
Texas     7100.0
ccc          NaN
Utah       500.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index=['bob','steve','jeff','ryan']
obj

bob      4
steve    7
jeff    -5
ryan     3
dtype: int64

In [40]:
data = {'state':['ohio','ohio','ohio','nevada','nevada','nevada'],'year':[2000,2001,2002,2001,2002,2003],'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
data
frame = pd.DataFrame(data)
frame

{'state': ['ohio', 'ohio', 'ohio', 'nevada', 'nevada', 'nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [48]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  nevada  2003  3.2

In [47]:
frame.head()  # get first 5 rows

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [51]:
frame2 = pd.DataFrame(data,columns=['year','state','pop'])
frame2

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9
5  2003  nevada  3.2

In [54]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [59]:
frame2.state = 'Jerry'

In [60]:
frame2

year  state  pop
0  2000  Jerry  1.5
1  2001  Jerry  1.7
2  2002  Jerry  3.6
3  2001  Jerry  2.4
4  2002  Jerry  2.9
5  2003  Jerry  3.2

In [64]:
frame2['year'] = np.arange(6.) #对整个列进行赋值

In [65]:
frame2

year  state  pop
0   0.0  Jerry  1.5
1   1.0  Jerry  1.7
2   2.0  Jerry  3.6
3   3.0  Jerry  2.4
4   4.0  Jerry  2.9
5   5.0  Jerry  3.2

In [66]:
frame2["eastern"] = frame2.year=='2.0'
frame2

D:\devs\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


year  state  pop  eastern
0   0.0  Jerry  1.5    False
1   1.0  Jerry  1.7    False
2   2.0  Jerry  3.6    False
3   3.0  Jerry  2.4    False
4   4.0  Jerry  2.9    False
5   5.0  Jerry  3.2    False

In [77]:
#del frame2['eastern']
frame2

year  state  pop
0   0.0  Jerry  1.5
1   1.0  Jerry  1.7
2   2.0  Jerry  3.6
3   3.0  Jerry  2.4
4   4.0  Jerry  2.9
5   5.0  Jerry  3.2

In [78]:
frame2.columns

Index(['year', 'state', 'pop'], dtype='object')

In [79]:
#索引对象

In [80]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index   #index 对象不可变

Index(['a', 'b', 'c'], dtype='object')

In [81]:
obj

a    0
b    1
c    2
dtype: int64

In [82]:
index[1:]  

Index(['b', 'c'], dtype='object')

In [83]:
#不可变可以使index 对象在多个数据结构间安全共享：
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [85]:
obj2.index is labels

True

In [86]:
#基本功能
#重新索引

In [88]:
 obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
 obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [108]:
obj2 = obj.reindex(['0','2'])

In [111]:
obj2

0   NaN
2   NaN
dtype: float64

In [112]:
obj3 = pd.Series(['blue','purple','yelloe'],index=[0,2,4])
obj3

0      blue
2    purple
4    yelloe
dtype: object

In [114]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yelloe
5    yelloe
dtype: object

In [115]:
#丢弃指定轴上的项

In [116]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [117]:
new_obj = obj.drop("c")

In [118]:
new_obj


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [119]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [120]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [126]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','new york'],columns=['one','two','three','four'])

In [127]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [128]:
data.drop(['colorado','ohio'])

one  two  three  four
utah        8    9     10    11
new york   12   13     14    15

In [131]:
data.drop('two',axis=1)

one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
new york   12     14    15

In [132]:
data.drop(['two','four'],axis='columns')

one  three
ohio        0      2
colorado    4      6
utah        8     10
new york   12     14

In [133]:
obj.drop('c',inplace=True)

In [134]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [135]:
#索引，选取，过滤

In [136]:
obj = pd.Series(np.arange(4),index=['a','b','c','d'])

In [137]:
obj

a    0
b    1
c    2
d    3
dtype: int32

In [138]:
obj["b"]

1

In [139]:
obj[1] #索引不是整数的时候，也可以根据整数取数

1

In [140]:
obj[2:4] 

c    2
d    3
dtype: int32

In [141]:
obj[obj<2]

a    0
b    1
dtype: int32

In [142]:
obj['b':'c']

b    1
c    2
dtype: int32

In [143]:
obj['b':'c']=5

In [144]:
obj

a    0
b    5
c    5
d    3
dtype: int32

In [145]:
obj[2:4]=50

In [146]:
obj

a     0
b     5
c    50
d    50
dtype: int32

In [147]:
obj[0:2]=500

In [148]:
obj

a    500
b    500
c     50
d     50
dtype: int32

In [149]:
#dataframe 和 series之间的运算

In [151]:
arr = np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [152]:
arr[0]

array([0., 1., 2., 3.])

In [153]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [157]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [158]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [160]:
series = frame.iloc[0]

In [161]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [162]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [163]:
series2

b    0
e    1
f    2
dtype: int64

In [164]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [165]:
series3 = frame['d']

In [166]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [167]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [168]:
#函数的隐射

In [170]:
frame = pd.DataFrame(np.random.randn(4, 3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [171]:
frame

b         d         e
Utah   -0.148366  0.270534 -1.486030
Ohio    0.430685  0.153223  0.535023
Texas  -0.718207  1.006872  1.144066
Oregon  0.121051 -0.017829  2.338946

In [172]:
np.abs(frame)

b         d         e
Utah    0.148366  0.270534  1.486030
Ohio    0.430685  0.153223  0.535023
Texas   0.718207  1.006872  1.144066
Oregon  0.121051  0.017829  2.338946

In [173]:
f = lambda x: x.max() - x.min()

In [174]:
frame.apply(f)

b    1.148892
d    1.024701
e    3.824976
dtype: float64

In [175]:
frame.apply(f, axis='columns')

Utah      1.756564
Ohio      0.381800
Texas     1.862273
Oregon    2.356775
dtype: float64

In [176]:
def f(x):return pd.Series([x.min(), x.max()], index=['min','max'])

In [177]:
frame.apply(f)

b         d         e
min -0.718207 -0.017829 -1.486030
max  0.430685  1.006872  2.338946

In [178]:
format = lambda x: '%.2f' % x

In [179]:
frame.applymap(format)

b      d      e
Utah    -0.15   0.27  -1.49
Ohio     0.43   0.15   0.54
Texas   -0.72   1.01   1.14
Oregon   0.12  -0.02   2.34

In [180]:
frame['e'].map(format)

Utah      -1.49
Ohio       0.54
Texas      1.14
Oregon     2.34
Name: e, dtype: object

In [181]:
# rank and sort

In [182]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [183]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [184]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [185]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'],columns=['d', 'a', 'b', 'c'])

In [186]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [187]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [188]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [189]:
obj = pd.Series([4, 7, -3, 2])

In [190]:
obj


0    4
1    7
2   -3
3    2
dtype: int64

In [191]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [192]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [193]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [194]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [195]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0,1]})

In [196]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [199]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [200]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [201]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [202]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [203]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [204]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0,1],'c':[-2, 5, 8, -2.5]})

In [205]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [206]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [207]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [208]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [209]:
obj.index.is_unique

False

In [210]:
obj['a']

a    0
a    1
dtype: int64

In [211]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a','b', 'b'])

In [212]:
df

0         1         2
a -0.373045  0.280425  1.082414
a -0.186220 -0.141926 -0.211747
b -1.681482 -0.880804 -0.428729
b -0.008338 -1.807556 -0.826998

In [213]:
df.loc['b']

0         1         2
b -1.681482 -0.880804 -0.428729
b -0.008338 -1.807556 -0.826998

In [214]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two'])

In [215]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [216]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [217]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [218]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [219]:
df.idxmax()

one    b
two    d
dtype: object

In [220]:
 df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [221]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [222]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [223]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [224]:
#red file

In [225]:
pd.options.display.max_rows = 10

In [227]:
result = pd.read_csv('ex6.csv')

In [228]:
result

aaa\tbbb\tccc\tddd\t
0   eee\tfff\thhh\tiii
1   jjj\tkkk\tlll\tmmm
2   nnn\tooo\tppp\tqqq
3   rrr\tsss\tttt\tuuu

In [230]:
result1 = pd.read_csv('ex6.csv',nrows=1)

In [231]:
result1

aaa\tbbb\tccc\tddd\t
0   eee\tfff\thhh\tiii

In [232]:
data = pd.read_csv('examples/ex5.csv')

FileNotFoundError: [Errno 2] File b'examples/ex5.csv' does not exist: b'examples/ex5.csv'

In [233]:
#json chuli

In [234]:
obj = """
{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
{"name": "Katie", "age": 38,
"pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [235]:
obj

'\n{"name": "Wes",\n"places_lived": ["United States", "Spain", "Germany"],\n"pet": null,\n"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},\n{"name": "Katie", "age": 38,\n"pets": ["Sixes", "Stache", "Cisco"]}]\n}\n'

In [236]:
import json

In [237]:
result = json.loads(obj)

In [238]:
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [239]:
asjson = json.dumps(result)

In [240]:
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [241]:
siblings = pd.DataFrame(result['siblings'], columns=['name','age'])

In [242]:
siblings

name  age
0  Scott   30
1  Katie   38

In [243]:
frame = pd.DataFrame({'a': np.random.randn(100)})

In [247]:
store = pd.HDFStore('mydata.h5')

In [248]:
store['obj1'] = frame

In [249]:
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [250]:
store['obj1']

a
0   0.629664
1   3.061355
2   0.245677
3  -1.267062
4  -0.943458
..       ...
95  0.558098
96  0.595896
97  0.398417
98 -0.115867
99 -0.409109

[100 rows x 1 columns]

In [251]:
store.put('obj2', frame, format='table')

In [252]:
store.select('obj2', where=['index >= 10 and index <= 15'])

a
10 -1.164978
11  1.520412
12 -0.041120
13 -1.352409
14  0.731500
15 -2.182113

In [256]:
store.close()

In [257]:
frame.to_hdf('mydata.h5', 'obj3', format='table')

In [ ]:
x

In [259]:
import requests
url = 'https://api.github.com/repos/pandasdev/pandas/issues'
resp = requests.get(url)

In [260]:
resp

<Response [404]>

In [261]:
#haha ,404                      O__O"…

In [262]:
data = resp.json()
data[0]['title']
issues = pd.DataFrame(data, columns=['number', 'title','labels', 'state'])
issures

KeyError: 0

In [263]:
#数据库交互

In [264]:
#busy ......,review it this weekend